name: build

on:
  push:
    branches: [ main ]
    tags-ignore:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3
    - name: Lint programs
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.47.3
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
